=== Ysmalee/RICM4_AR_Projet_aplp/Configurations/Server.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT server (port,(service | agent)*)>
	
<!ELEMENT port EMPTY>
<!ATTLIST port value CDATA #REQUIRED>
	
<!ELEMENT service EMPTY>
<!ATTLIST service name CDATA #REQUIRED>
<!ATTLIST service codebase CDATA #IMPLIED>
<!ATTLIST service class CDATA #REQUIRED>
<!ATTLIST service args CDATA #IMPLIED>
	
<!ELEMENT agent (etape)*>
<!ATTLIST agent class CDATA #REQUIRED>
<!ATTLIST agent codebase CDATA #IMPLIED>
<!ATTLIST agent args CDATA #IMPLIED>
	
<!ELEMENT etape EMPTY>
<!ATTLIST etape server CDATA #REQUIRED>
<!ATTLIST etape action CDATA #REQUIRED>

=== Ysmalee/RICM4_AR_Projet_aplp/Configurations/LookForHotel.MainServer.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE HTML PUBLIC  "-//W3C//DTD HTML 4.0 Transitional//EN" "Server.dtd"> 
<server>
	<port value="4000"/>
	<agent class="jus.aor.mobilagent.agent.LookForHotel" codebase="jar/LookForHotel.jar" args="Paris">
		<etape server="mobilagent://localhost:4001/" action="doHotel" />
		<etape server="mobilagent://localhost:4002/" action="doHotel" />
		<etape server="mobilagent://localhost:4003/" action="doHotel" />
		<etape server="mobilagent://localhost:4004/" action="doHotel" />
		<etape server="mobilagent://localhost:4005/" action="doAnnuaire"/>
	</agent>
</server>
